# Notes on Manipulator Kinematics

First you need to import numpy, the roboticstoolbox and a library called spatialmath as follows

In [2]:
import numpy as np
import roboticstoolbox as rtb
import spatialmath as sm

The next step is to start playing with the toolbox. Using the robotic Toolbox for Python we will create an ET. Lets try the following:
* A varible rotation around the x-axis
* A constant rotation around the x-axis by 90 degrees

In [3]:
# We are going to create a variable rotation about the x-axis
rx_var = rtb.ET.Rx()

# This is a constant rotation around the x-axis by 90 degrees
rx_cons = rtb.ET.Rx(np.pi / 2) # See that we use radians, be careful with that

# Let's print each of the ET's and the format they have when printing
print(f"The variable rotation around x is: {rx_var}")
print(f"The variable rotation around x has a type: {type(rx_var)}")
print(f"The constant rotation around x is: {rx_cons}")
print(f"The constant rotation around x has a type: {type(rx_cons)}")

The variable rotation around x is: Rx(q)
The variable rotation around x has a type: <class 'roboticstoolbox.robot.ET.ET'>
The constant rotation around x is: Rx(90°)
The constant rotation around x has a type: <class 'roboticstoolbox.robot.ET.ET'>


After creating a variable, we have to calculate the transformation. Ther are different things!
We are going to do the following:
* use the .A method to calculate the transformation for the CONSTANT rotation and see what it returns
* Use the spatialmath package to create an SE3 array (also helps for visualization)
As the type of a ET is in fact, a ET object in Python, the .A method is applied to this objects

In [4]:
# We are going to calculate the transform resulting from, the constant rotation ET using the .A method
transform = rx_cons.A() # It should return a numpy array

# Let's use the spatialmath package to create the SE3 object from the numpy array
sm_transform = sm.SE3(transform)

# Now print the results of each variable and see the benefits of spatialmath
print(f"The transformation shown as a numpy array is:\n{transform}")
print(f"The transformation shown as a numpy array has a type: {type(transform)}")
print(f"The transformation shown as a SE3 is:\n{sm_transform}")
print(f"The transformation shown as a SE3 has a type: {type(sm_transform)}")

The transformation shown as a numpy array is:
[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
The transformation shown as a numpy array has a type: <class 'numpy.ndarray'>
The transformation shown as a SE3 is:
   1         0         0         0         
   0         0        -1         0         
   0         1         0         0         
   0         0         0         1         

The transformation shown as a SE3 has a type: <class 'spatialmath.pose3d.SE3'>


Now we are going to calculate the transform resulting from the variable rotation. For this, we must supply a joint coordinate when using the A. method. 
* Remember to supply a coordinate system for variable rotations (and translations)

In [5]:
# This is just for the example. We are going to make a joint at 45 degrees
q = np.pi / 4
transform = rx_var.A(q)
sm_transform = sm.SE3(transform)

# Now print the results of each variable and see the benefits of spatialmath
print(f"The transformation shown as a numpy array is:\n{transform}")
print(f"The transformation shown as a SE3 is:\n{sm_transform}")

The transformation shown as a numpy array is:
[[ 1.          0.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]
The transformation shown as a SE3 is:
   1         0         0         0         
   0         0.7071   -0.7071    0         
   0         0.7071    0.7071    0         
   0         0         0         1         



Check if the same results are obtained when creating a joint at 90 degrees and apply this to the variable rotation. The result has to be the same as the one for the constant rotation

In [6]:
# This is just for the example. We are going to make a joint at 45 degrees
q = np.pi / 2
transform = rx_var.A(q)
sm_transform = sm.SE3(transform)

# Now print the results of each variable and see the benefits of spatialmath
print(f"The transformation shown as a numpy array is:\n{transform}")
print(f"The transformation shown as a SE3 is:\n{sm_transform}")

The transformation shown as a numpy array is:
[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
The transformation shown as a SE3 is:
   1         0         0         0         
   0         0        -1         0         
   0         1         0         0         
   0         0         0         1         



Now let's create a prismatic joint

In [7]:
# Create a variable translation around the y-axis
ty_var = rtb.ET.ty()

# Create a constant translation along the y-axis by 25 cm
ty_cons = rtb.ET.ty(0.25) # Hint: rtb uses meters as unit, be careful

print(ty_var)
print(ty_cons)

ty(q)
ty(0.25)


Now calculate thre transformation. We will create both (it means numpy array and SE3 object), but we are just going to show the SE3 representation as it is easier to read

In [8]:
# Calculate the transform for the constant translation.
transform = ty_cons.A()
sm_transform = sm.SE3(transform)

print(f"SE3:\n{sm_transform}")

SE3:
   1         0         0         0         
   0         1         0         0.25      
   0         0         1         0         
   0         0         0         1         



Now calculate the transformatio for the variable translation in y-axis. Remember to add the amount of translation you would like to achieve or define

In [9]:
# Make the joint at 15 cm
q = 0.15 # Remember it is in meters
transform = ty_var.A(q)
sm_transform = sm.SE3(transform)
print(f"SE3:\n{sm_transform}")

SE3:
   1         0         0         0         
   0         1         0         0.15      
   0         0         1         0         
   0         0         0         1         



*Refer to the schematic of the 7 DOF Franka Emika of the Peter's article to follow the next example*


In [10]:
# Note for for E7 and E11 in the figure above and code below, we use flip=True
# as the variable rotation is in the negative direction.

E1 = rtb.ET.tz(0.333)
E2 = rtb.ET.Rz()
E3 = rtb.ET.Ry()
E4 = rtb.ET.tz(0.316)
E5 = rtb.ET.Rz()
E6 = rtb.ET.tx(0.0825)
E7 = rtb.ET.Ry(flip=True)
E8 = rtb.ET.tx(-0.0825)
E9 = rtb.ET.tz(0.384)
E10 = rtb.ET.Rz()
E11 = rtb.ET.Ry(flip=True)
E12 = rtb.ET.tx(0.088)
E13 = rtb.ET.Rx(np.pi)
E14 = rtb.ET.tz(0.107)
E15 = rtb.ET.Rz()

# We can create and ETS in a number of ways

# Firstly if we use the * operator between two or more ETs, we get an ETS
ets1 = E1 * E2 * E3

# Secondly, we can use the ETS constructor and pass in a list of ETs
ets2 = rtb.ETS([E1, E2, E3])

# We can also use the * operator between ETS' and ETs to concatenate
ets3 = ets2 * E4
ets4 = ets2 * rtb.ETS([E4, E5])

print(ets1)
print(ets2)
print(ets3)
print(ets4)


tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1)
tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1)
tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1) ⊕ tz(0.316)
tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1) ⊕ tz(0.316) ⊕ Rz(q0)


After that example, let's represent the Panda robot by incorporatong all 15 ETS into a single ones

In [11]:
panda = E1 * E2 * E3 * E4 * E5 * E6 * E7 * E8 * E9 * E10 * E11 * E12 * E13 * E14 * E15
panda_ = rtb.ETS([E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15])

# Let's print hthe ETS
print(panda)
print(f"Are the 2 ETS the same (for the computer): {panda==panda_}")


tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1) ⊕ tz(0.316) ⊕ Rz(q2) ⊕ tx(0.0825) ⊕ Ry(-q3) ⊕ tx(-0.0825) ⊕ tz(0.384) ⊕ Rz(q4) ⊕ Ry(-q5) ⊕ tx(0.088) ⊕ Rx(180°) ⊕ tz(0.107) ⊕ Rz(q6)
Are the 2 ETS the same (for the computer): True


The ETS class has many usefull properties, lets check some of them

In [12]:
# Check the number of jonts in the panda model. ETS.n property
print(f"The panda has {panda.n} joints")

# Check the number of ETs in the panda model. ETS.m property
print(f"The panda has {panda.m} ETs")

# Let's access an ET from the ETS as if the ETS were a Python list
print(f"The second ET in the ETS is {panda[1]}")

# Let's check if E2 is the same as panda[1]
print(f"The second ET in the ETS is {rtb.ETS(E2)}, Are the same?: {panda[1]==rtb.ETS(E2)}")



The panda has 7 joints
The panda has 15 ETs
The second ET in the ETS is Rz(q0)
The second ET in the ETS is Rz(q), Are the same?: False


In [13]:
# They are not the same because when a variable ET is added to an ETS, it is assigned a jindex, which is short for joint index. When given an array of joint coordinates (i.e. joint angles), the ETS will use the jindices of each
print(f"The first variable joint has a jindex of {panda[1].jindex}, while the second has a jindex of {panda[2].jindex}")

The first variable joint has a jindex of 0, while the second has a jindex of 1


I have a question. Why the first variable joint is accesed with panda[1].jindex, should it start from 0?

In [14]:
# Other thing is that we can extract all of the variable ETs from the panda model as a list
print(f"All variable links in the Panda ETS:\n{panda.joints()}")
print(f"The number of variable ETs is {len(panda.joints())}")

All variable links in the Panda ETS:
[ET.Rz(jindex=0), ET.Ry(jindex=1), ET.Rz(jindex=2), ET.Ry(jindex=3, flip=True), ET.Rz(jindex=4), ET.Ry(jindex=5, flip=True), ET.Rz(jindex=6)]
The number of variable ETs is 7


<br>

<a id='fk'></a>
### 1.2 Forward Kinematics
---

Using the methodology described in the article, we can calculate the forward kinematics of the panda model

In [15]:
# First we define the joint coordinates q, to calculate the forward kinematics at
q = np.array([0, -0.3, 0, -2.2, 0, 2, 0.79]) # Units in radians

# Allocate the resulting forward kinematics array
fk = np.eye(4)

# Let's loop over the ETs in the panda
for et in panda:
    if et.isjoint:
        # This means ET is a variable joint
        # We use the q array to specify the joint angle for the variable ET
        fk = fk @ et.A(q[et.jindex])
    else:
        # This means ET is static
        fk = fk @ et.A()

# Print the result as a SE3 object to visualize better
print(f"The resulting transformation base-end_effector is:\n{sm.SE3(fk)}")

The resulting transformation base-end_effector is:
   0.7003   -0.7068    0.09983   0.4737    
  -0.7104   -0.7038    0         0         
   0.07027  -0.07092  -0.995     0.5155    
   0         0         0         1         



The ETS class has the .fkine, which calculates the forward kinematics.
The .fkine method returns a SE3 object

In [16]:
fkine = panda.fkine(q)
print(f"The fkine method: \n{panda.fkine(q)}")

The fkine method: 
   0.7003   -0.7068    0.09983   0.4737    
  -0.7104   -0.7038    0         0         
   0.07027  -0.07092  -0.995     0.5155    
   0         0         0         1         



In [17]:
# Let's see if the loop method is the same as the fkine method (for the computer)
# Dont forget to convert the array to SE3
print(f"Are both forward kinematics methods the same?: {sm.SE3(fk) == fkine}")

Are both forward kinematics methods the same?: True


If you would like to have in return a numpy array, use the .eval method.


In [20]:
evalm = panda.eval(q)

# Check if fk and eval are the same
print(f"Are both forward kinematics methods the same?: \n{fk == evalm}")

Are both forward kinematics methods the same?: 
[[ True  True False  True]
 [ True  True  True  True]
 [False False  True  True]
 [ True  True  True  True]]


In [19]:
# Lets print and understant why?
print(f"Numpy array with a loop: \n{fk}")
print(f"Numpy array with .eval method: \n{evalm}")

Numpy array with a loop: 
[[ 7.00329021e-01 -7.06804465e-01  9.98334166e-02  4.73724040e-01]
 [-7.10353272e-01 -7.03845316e-01 -1.22464680e-16 -1.31037208e-17]
 [ 7.02672827e-02 -7.09169942e-02 -9.95004165e-01  5.15513206e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Numpy array with .eval method: 
[[ 7.00329021e-01 -7.06804465e-01  9.98334166e-02  4.73724040e-01]
 [-7.10353272e-01 -7.03845316e-01 -1.22464680e-16 -1.31037208e-17]
 [ 7.02672827e-02 -7.09169942e-02 -9.95004165e-01  5.15513206e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
